syntax = "proto3";

import "google/protobuf/empty.proto";

package cursos;

message Curso {
  string codigo = 1;
  string nombre = 2;
  string docente = 3;
}

message CursoRequest {
  string codigo = 1;
}

message CursoResponse {
  Curso curso = 1;
}

message CursosList {
  repeated Curso cursos = 1;
}

service CursoService {
  rpc AgregarCurso (Curso) returns (CursoResponse);
  rpc ObtenerCurso (CursoRequest) returns (CursoResponse);
  rpc ListarCursos (google.protobuf.Empty) returns (CursosList);
}
