syntax = "proto3";

import "google/protobuf/empty.proto";

package estudiantes;

message Estudiante {
  string ci = 1;
  string nombres = 2;
  string apellidos = 3;
  string carrera = 4;
}

message EstudianteRequest {
  string ci = 1;
}

message EstudianteResponse {
  Estudiante estudiante = 1;
}

message EstudiantesList {
  repeated Estudiante estudiantes = 1;
}

service EstudianteService {
  rpc AgregarEstudiante (Estudiante) returns (EstudianteResponse);
  rpc ObtenerEstudiante (EstudianteRequest) returns (EstudianteResponse);
  rpc ListarEstudiantes (google.protobuf.Empty) returns (EstudiantesList);
}

