input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter { }

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microservicio-logs-%{+YYYY.MM.dd}"
    ssl => false
    ecs_compatibility => disabled
    ilm_enabled => false
  }
  stdout { codec => rubydebug }
}
